In [1]:
import numpy as np 

In [3]:
n1=np.array([1,7,13,105])
print(n1)
print(f"Type ={type(n1)}")

[  1   7  13 105]
Type =<class 'numpy.ndarray'>


In [10]:
#Q2
n1=np.array([4,8])
n2=np.array([2,8])
print("Original Num :")
print(n1)
print(n2)
print("Comparison - greater :")
print(np.greater(n1,n2))
print("Comparison -greater equal")
print(np.greater_equal(n1,n2))
print("Comparison -less :")
print(np.less(n1,n2))
print("Comparison -less equal")
print(np.less_equal(n1,n2))

Original Num :
[4 8]
[2 8]
Comparison - greater :
[ True False]
Comparison -greater equal
[ True  True]
Comparison -less :
[False False]
Comparison -less equal
[False  True]


In [28]:
#Q3
n1=np.zeros(10)
n2=np.ones(10)
n3=np.ones(10)*5
n4=np.ones(10)*20
n5=np.ones(10)*50
print(n5)
print(n4)
print(n3)
print(n2)
print(n1)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
#Q4
n1=np.arange(30,70)
print(n1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [32]:
#Q5
n1=np.arange(50,96)
print(n1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [33]:
#Q6
n1=np.arange(20,80,2)
print(n1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [34]:
#Q7
n1=np.arange(20,80,3)
print(n1)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77]


In [39]:
#Q8
n1=np.random.randint(10,40,15)
print(n1)

[37 31 36 13 10 19 10 21 26 17 16 14 21 39 27]


In [40]:
#Q9
n1=np.random.randint(30,50,10)
print(n1)

[49 47 35 49 41 36 33 38 38 34]


In [41]:
#Q10
n1=np.random.randint(50,90,20)
print(n1)

[52 71 61 57 66 80 80 83 59 54 86 72 78 76 72 73 51 84 86 83]


In [47]:
#Q11
n1=np.array([10,20,30,40])
n2=np.array([11,22,33,44])
print("Addition :")
print(n1+n2)
print("Subtraction :")
print(n2-n1)
print("Multiplication:")
print(n1*n2)
print("Division :")
print(n2/n1)


Addition :
[21 42 63 84]
Subtraction :
[1 2 3 4]
Multiplication:
[ 110  440  990 1760]
Division :
[1.1 1.1 1.1 1.1]


In [48]:
#Q12
n1=np.arange(10,22).reshape((3,4))
print(n1)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [50]:
#Q13
# eye function to create a 2 dimensional 
n1=np.eye(3)
print(n1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
#Q14
n1=np.arange(1,13).reshape((3,4))
print("Original :")
print(n1)
print("NUmber of Rows and Columns :")
print(n1.shape)

Original :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
NUmber of Rows and Columns :
(3, 4)


In [64]:
#Q15
#daig function to print diagonal values
n1=np.diag([1,2,3,4,5])
print(n1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [70]:
#Q16
n1=np.random.random((3,3,3))
print(n1)

[[[0.02753321 0.26050723 0.34278919]
  [0.14691838 0.28734241 0.96574271]
  [0.82485584 0.38150477 0.60627103]]

 [[0.13480142 0.88502123 0.41762492]
  [0.70106543 0.00866602 0.02085954]
  [0.10596713 0.09229156 0.03341773]]

 [[0.70436763 0.95486646 0.40361444]
  [0.70564345 0.78450059 0.59259174]
  [0.16143475 0.21329913 0.35026243]]]


In [71]:
#Q17
n1=np.random.random((2,3,4))
print(n1)

[[[0.40546636 0.52371681 0.93728539 0.82245068]
  [0.55122726 0.84133686 0.72707966 0.72980914]
  [0.43047949 0.41634433 0.02234826 0.68921227]]

 [[0.84982755 0.88544876 0.48326475 0.53604668]
  [0.01522437 0.07435071 0.64852134 0.42600628]
  [0.55394524 0.96131646 0.65895119 0.84043215]]]


In [72]:
#Q18
n1=[10,20,30,40,50]
print("Orignal list :")
print(n1)
n2=np.array(n1)
print("One dimesion :")
print(n2)

Orignal list :
[10, 20, 30, 40, 50]
One dimesion :
[10 20 30 40 50]


In [73]:
#Q19
n1=np.arange(2,11).reshape((3,3))
print(n1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [74]:
#Q20
n1=np.arange(12,39)
print(n1)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [80]:
#Q21
n1=np.array([10,20,30,40,50])
print("Original :")
print(n1)
#To reverse "flip" function is used !
n2=np.flip(n1)
print("Reverse :")
print(n2)

Original :
[10 20 30 40 50]
Reverse :
[50 40 30 20 10]


In [85]:
#Q22
n1=np.array([10,20,30,40,50])
print(n1)
n2=np.asfarray(n1)
print(n2)

[10 20 30 40 50]
[10. 20. 30. 40. 50.]


In [88]:
#Q23
n1=[10,20,30,40,50,60]
print(n1)
n2=np.array(n1)
print(n2)

[10, 20, 30, 40, 50, 60]
[10 20 30 40 50 60]


In [92]:
#Q24
n1=np.arange(7)
print(n1)
print("Element wise remainder of divison :")
print(np.remainder(n1,2))

[0 1 2 3 4 5 6]
Element wise remainder of divison :
[0 1 0 1 0 1 0]


In [93]:
#Q25
n1=np.arange(20,50)
print(n1)
print("Element wise remainder of divison by 3 :")
print(np.remainder(n1,3))

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
Element wise remainder of divison by 3 :
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
